# Numpy

## Why?

* Tensors <=> ndarrays
* Tensor Operations
* Vectorization
* Efficiency
* Other Libraries

In [14]:
import numpy as np

## 객체와 ndarrays

In [15]:
l = [1, 2, 3] # list => object

In [16]:
l.append(4) # "append" method

In [17]:
print(l)

[1, 2, 3, 4]


* `dir()`

In [18]:
for attr in dir(l):
    print(attr)

__add__
__class__
__class_getitem__
__contains__
__delattr__
__delitem__
__dir__
__doc__
__eq__
__format__
__ge__
__getattribute__
__getitem__
__gt__
__hash__
__iadd__
__imul__
__init__
__init_subclass__
__iter__
__le__
__len__
__lt__
__mul__
__ne__
__new__
__reduce__
__reduce_ex__
__repr__
__reversed__
__rmul__
__setattr__
__setitem__
__sizeof__
__str__
__subclasshook__
append
clear
copy
count
extend
index
insert
pop
remove
reverse
sort


In [19]:
d = {'a': 0, 'b': 1, 'c': 2}
for attr in dir(d):
    print(attr)

__class__
__class_getitem__
__contains__
__delattr__
__delitem__
__dir__
__doc__
__eq__
__format__
__ge__
__getattribute__
__getitem__
__gt__
__hash__
__init__
__init_subclass__
__ior__
__iter__
__le__
__len__
__lt__
__ne__
__new__
__or__
__reduce__
__reduce_ex__
__repr__
__reversed__
__ror__
__setattr__
__setitem__
__sizeof__
__str__
__subclasshook__
clear
copy
fromkeys
get
items
keys
pop
popitem
setdefault
update
values


In [20]:
a = [10, 20, 30, 40, 50]
b = [1.5, 2.5, 3.5, 4.5]
c = ['a', 'b','c','d']
for attr in zip(dir(a), dir(b), dir(c)):
    print(attr)

('__add__', '__add__', '__add__')
('__class__', '__class__', '__class__')
('__class_getitem__', '__class_getitem__', '__class_getitem__')
('__contains__', '__contains__', '__contains__')
('__delattr__', '__delattr__', '__delattr__')
('__delitem__', '__delitem__', '__delitem__')
('__dir__', '__dir__', '__dir__')
('__doc__', '__doc__', '__doc__')
('__eq__', '__eq__', '__eq__')
('__format__', '__format__', '__format__')
('__ge__', '__ge__', '__ge__')
('__getattribute__', '__getattribute__', '__getattribute__')
('__getitem__', '__getitem__', '__getitem__')
('__gt__', '__gt__', '__gt__')
('__hash__', '__hash__', '__hash__')
('__iadd__', '__iadd__', '__iadd__')
('__imul__', '__imul__', '__imul__')
('__init__', '__init__', '__init__')
('__init_subclass__', '__init_subclass__', '__init_subclass__')
('__iter__', '__iter__', '__iter__')
('__le__', '__le__', '__le__')
('__len__', '__len__', '__len__')
('__lt__', '__lt__', '__lt__')
('__mul__', '__mul__', '__mul__')
('__ne__', '__ne__', '__ne__')


## Special Methods

In [30]:
print(a.__add__(b)) # list
print(a + b)

[10, 20, 30, 40, 50, 1.5, 2.5, 3.5, 4.5]
[10, 20, 30, 40, 50, 1.5, 2.5, 3.5, 4.5]


In [28]:
z1, z2 = 10, 20
print(z1.__add__(z2)) # integer
print(z1 + z2)

30
30


In [27]:
print(len(a))
print(a.__len__())

5
5


In [34]:
r1, r2, r3, r4, r5 = 1.2, 3.5, 4.2, 5.2, 5.1
result1 = (r1+r2)**r3 - (r4/r5)
result2 = ((r1.__add__(r2)).__pow__(r3)).__sub__(r4.__truediv__(r5))
print(result1)
print(result2)

663.9640971641916
663.9640971641916


In [35]:
a_list = [1,2,3]
b_list = [4,5,6]

In [36]:
a_list + b_list == a_list.__add__(b_list)

True

In [40]:
print(a_list + b_list)

[1, 2, 3, 4, 5, 6]


In [37]:
a_np = np.array(a_list)
b_np = np.array(b_list)

In [42]:
a_np.__add__(b_np) == a_np + b_np

array([ True,  True,  True])

## ndarray

In [46]:
a_np = np.array([1,2,3])

In [47]:
for attr in dir(a_np):
    print(attr)

T
__abs__
__add__
__and__
__array__
__array_finalize__
__array_function__
__array_interface__
__array_prepare__
__array_priority__
__array_struct__
__array_ufunc__
__array_wrap__
__bool__
__class__
__class_getitem__
__complex__
__contains__
__copy__
__deepcopy__
__delattr__
__delitem__
__dir__
__divmod__
__dlpack__
__dlpack_device__
__doc__
__eq__
__float__
__floordiv__
__format__
__ge__
__getattribute__
__getitem__
__gt__
__hash__
__iadd__
__iand__
__ifloordiv__
__ilshift__
__imatmul__
__imod__
__imul__
__index__
__init__
__init_subclass__
__int__
__invert__
__ior__
__ipow__
__irshift__
__isub__
__iter__
__itruediv__
__ixor__
__le__
__len__
__lshift__
__lt__
__matmul__
__mod__
__mul__
__ne__
__neg__
__new__
__or__
__pos__
__pow__
__radd__
__rand__
__rdivmod__
__reduce__
__reduce_ex__
__repr__
__rfloordiv__
__rlshift__
__rmatmul__
__rmod__
__rmul__
__ror__
__rpow__
__rrshift__
__rshift__
__rsub__
__rtruediv__
__rxor__
__setattr__
__setitem__
__setstate__
__sizeof__
__str__
__sub__
__su

### Element-wise operations of ndarrays

* $\vec{u}^{\,T} = \begin{array}{clr}( 1 & 2 & 3 ) \end{array}$
* $\vec{v}^{\,T} = \begin{array}{clr}( 4 & 5 & 6 ) \end{array}$
* $\vec{w}^{\,T} = \vec{u}^{\,T} + \vec{v}^{\,T}$
    $ = \begin{array}{clr}( 1 & 2 & 3 ) \end{array} + \begin{array}{clr}( 4 & 5 & 6 ) \end{array}$
    $ = \begin{array}{clr}( 5 & 7 & 9 ) \end{array}$

In [50]:
u = [1,2,3]
v = [4,5,6]
w = [0] * len(u)

for idx in range(len(u)):
    w[idx] = u[idx] + v[idx]

print(w)

[5, 7, 9]


In [52]:
u_np = np.array([1,2,3])
v_np = np.array([4,5,6])
w_np = u_np + v_np

print(w_np)

[5 7 9]


In [57]:
u = [[1,2,3], [4,5,6], [7,8,9]]
v = [[11,12,13], [14,15,16], [17,18,19]]
w_row, w_col = len(u), len(u[0])

w = [[0]*w_row for _ in range(w_col)]

for r_idx in range(w_row):
    for c_idx in range(w_col):
        w[r_idx][c_idx] = u[r_idx][c_idx] + v[r_idx][c_idx]

print(w)

[[12, 14, 16], [18, 20, 22], [24, 26, 28]]


In [58]:
u_np = np.array(u)
v_np = np.array(v)
w_np = u_np + v_np

print(w_np)

[[12 14 16]
 [18 20 22]
 [24 26 28]]
