# Introduction to Vectors and Matrices

In [1]:
import numpy as np
x = np.array([[1,0,4],[3,3,1]])
y = np.array([[2,5],[1,1],[3,2]])
x.dot(y)

array([[14, 13],
       [12, 20]])

# Basics of NumPy Array Object

In [2]:
import numpy as np
x = np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
print("We just create a ", type(x))

We just create a  <class 'numpy.ndarray'>


In [6]:
print("Our template has shape as" ,x.shape)

Our template has shape as (2, 3)


In [7]:
print("Total size is",x.size)

Total size is 6


In [8]:
print("The dimension of our array is " ,x.ndim)

The dimension of our array is  2


In [9]:
print("Data type of elements are",x.dtype)

Data type of elements are int32


In [10]:
print("It consumes",x.nbytes,"bytes")

It consumes 24 bytes


In [12]:
x = np.array([[1,2,3],[4,5,6]], dtype = float)
print(x)
print(x.nbytes)

[[1. 2. 3.]
 [4. 5. 6.]]
48


In [14]:
x = np.array([[1,2,3],[4,5,6]], dtype = complex)
print(x)
print(x.nbytes)

[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]
96


In [16]:
x = np.array([[1,2,3],[4,-5,6]], dtype = np.uint32)
print(x)
print(x.nbytes)

[[         1          2          3]
 [         4 4294967291          6]]
24


In [17]:
x = np.array([[1,2,3],[4,5,6]], dtype = np.int64)
print("int64 comsues",x.nbytes, "bytes")
x = np.array([[1,2,3],[4,5,6]], dtype = np.int32)
print("int32 comsues",x.nbytes, "bytes")

int64 comsues 48 bytes
int32 comsues 24 bytes


In [18]:
x_copy = np.array(x, dtype = float)
x_copy 

array([[1., 2., 3.],
       [4., 5., 6.]])

In [19]:
x_copy_int = x_copy.astype(int)
x_copy_int

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
x_copy

array([[1., 2., 3.],
       [4., 5., 6.]])

In [21]:
Data_Cancer = np.random.rand(100000,100)
print(type(Data_Cancer))
print(Data_Cancer.dtype)
print(Data_Cancer.nbytes)
Data_Cancer_New = np.array(Data_Cancer, dtype = np.float32)
print(Data_Cancer_New.nbytes)

<class 'numpy.ndarray'>
float64
80000000
40000000


# NumPy Array Operations

In [22]:
my_list = [2, 14, 6, 8]
my_array = np.asarray(my_list)
type(my_array)

numpy.ndarray

In [23]:
my_array +2

array([ 4, 16,  8, 10])

In [24]:
my_array -1

array([ 1, 13,  5,  7])

In [25]:
my_array *2

array([ 4, 28, 12, 16])

In [26]:
my_array /2

array([1., 7., 3., 4.])

In [27]:
second_array = np.zeros(4) + 3
second_array 

array([3., 3., 3., 3.])

In [28]:
my_array - second_array 

array([-1., 11.,  3.,  5.])

In [29]:
second_array / my_array 

array([1.5       , 0.21428571, 0.5       , 0.375     ])

In [30]:
second_array = np.ones(4)+3
second_array

array([4., 4., 4., 4.])

In [31]:
my_array - second_array 

array([-2., 10.,  2.,  4.])

In [32]:
second_array / my_array 

array([2.        , 0.28571429, 0.66666667, 0.5       ])

In [33]:
second_array = np.identity(4)
second_array

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [34]:
second_array = np.identity(4)+3
second_array

array([[4., 3., 3., 3.],
       [3., 4., 3., 3.],
       [3., 3., 4., 3.],
       [3., 3., 3., 4.]])

In [35]:
my_array - second_array 

array([[-2., 11.,  3.,  5.],
       [-1., 10.,  3.,  5.],
       [-1., 11.,  2.,  5.],
       [-1., 11.,  3.,  4.]])

In [36]:
second_array / my_array 

array([[2.        , 0.21428571, 0.5       , 0.375     ],
       [1.5       , 0.28571429, 0.5       , 0.375     ],
       [1.5       , 0.21428571, 0.66666667, 0.375     ],
       [1.5       , 0.21428571, 0.5       , 0.5       ]])

In [37]:
x = np.arange(3,7,0.5)
x

array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5])

In [38]:
x = np.linspace(1.2, 40.5, num=20)
x

array([ 1.2       ,  3.26842105,  5.33684211,  7.40526316,  9.47368421,
       11.54210526, 13.61052632, 15.67894737, 17.74736842, 19.81578947,
       21.88421053, 23.95263158, 26.02105263, 28.08947368, 30.15789474,
       32.22631579, 34.29473684, 36.36315789, 38.43157895, 40.5       ])

In [39]:
np.geomspace(1, 625, num=5)

array([  1.,   5.,  25., 125., 625.])

In [40]:
np.logspace(3, 4, num=5)

array([ 1000.        ,  1778.27941004,  3162.27766017,  5623.4132519 ,
       10000.        ])

In [41]:
np.logspace(np.log10(3) , np.log10(4) , num=5)

array([3.        , 3.2237098 , 3.46410162, 3.72241944, 4.        ])

In [42]:
x = np.array([1,2,3,4])
y = np.array([1,3,4,4])
x == y 

array([ True, False, False,  True])

In [43]:
x = np.array([1,2,3,4])
y = np.array([1,3,4,4])
np.array_equal(x,y)

False

In [44]:
x = np.array([1,2,3,4])
y = np.array([1,3,4,4])
x < y 

array([False,  True,  True, False])

In [45]:
x = np.array([0, 1, 0, 0], dtype=bool)
y = np.array([1, 1, 0, 1], dtype=bool)
np.logical_or(x,y)

array([ True,  True, False,  True])

In [46]:
np.logical_and(x,y)

array([False,  True, False, False])

In [47]:
x = np.array([12,16,57,11])
np.logical_or(x < 13, x > 50)

array([ True, False,  True,  True])

In [48]:
x = np.array([1, 2, 3,4 ])
np.exp(x)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [49]:
np.log(x)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [50]:
np.sin(x)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [51]:
x = np.arange(9)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [52]:
x = np.arange(9).reshape((3, 3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [53]:
x.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [54]:
x = np.arange(6).reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [55]:
x.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [56]:
x = np.arange(9).reshape((3,3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [57]:
np.sum(x)

36

In [58]:
np.amin(x)

0

In [59]:
np.amax(x)

8

In [60]:
np.amin(x, axis=0)

array([0, 1, 2])

In [61]:
np.amin(x, axis=1)

array([0, 3, 6])

In [62]:
np.percentile(x, 80)

6.4

In [63]:
x = np.array([1,-21,3,-3])
np.argmax(x)

2

In [64]:
np.argmin(x)

1

In [65]:
x = np.array([[2, 3, 5], [20, 12, 4]])
x

array([[ 2,  3,  5],
       [20, 12,  4]])

In [66]:
np.mean(x)

7.666666666666667

In [67]:
np.mean(x, axis=0)

array([11. ,  7.5,  4.5])

In [68]:
np.mean(x, axis=1)

array([ 3.33333333, 12.        ])

In [69]:
np.median(x)

4.5

In [70]:
np.std(x)

6.394442031083626

# Working with Multidimensional Arrays

In [71]:
c = np.ones((4, 4))
c*c

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [72]:
c.dot(c)

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [73]:
y = np.arange(15).reshape(3,5) 
x = np.arange(10).reshape(2,5)
new_array = np.vstack((y,x))
new_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])

In [74]:
y = np.arange(15).reshape(5,3) 
x = np.arange(10).reshape(5,2)
new_array = np.hstack((y,x))
new_array

array([[ 0,  1,  2,  0,  1],
       [ 3,  4,  5,  2,  3],
       [ 6,  7,  8,  4,  5],
       [ 9, 10, 11,  6,  7],
       [12, 13, 14,  8,  9]])

In [75]:
from scipy import stats
x= np.random.rand(100,10)
n, min_max, mean, var, skew, kurt = stats.describe(x)
new_array = np.vstack((mean,var,skew,kurt,min_max[0],min_max[1]))
new_array.T

array([[ 4.94844423e-01,  8.83343273e-02,  1.97528059e-01,
        -1.18893649e+00,  4.69335293e-03,  9.99164963e-01],
       [ 5.07034053e-01,  8.33114568e-02, -5.78819873e-02,
        -1.15559419e+00,  6.31065176e-04,  9.92035568e-01],
       [ 5.04416249e-01,  8.75203672e-02,  4.30498096e-02,
        -1.20319239e+00,  7.80719451e-03,  9.95385710e-01],
       [ 4.82893280e-01,  7.71607954e-02,  6.62246896e-02,
        -1.06294714e+00,  1.39209335e-03,  9.98800429e-01],
       [ 5.14220861e-01,  6.94232633e-02, -3.82534935e-03,
        -1.10322411e+00,  3.88708298e-02,  9.80765211e-01],
       [ 4.53875787e-01,  9.32601008e-02,  2.22205646e-01,
        -1.22737747e+00,  1.27800655e-03,  9.89473001e-01],
       [ 5.43622182e-01,  7.77735777e-02, -2.50695851e-01,
        -9.69951428e-01,  1.21603037e-02,  9.96582966e-01],
       [ 4.70037072e-01,  8.45127820e-02,  2.29650565e-01,
        -1.25223740e+00,  2.23958741e-03,  9.91179468e-01],
       [ 4.48632557e-01,  7.92329532e-02,  1.905

In [76]:
import numpy.ma as ma
x = np.arange(6)
print(x.mean())
masked_array = ma.masked_array(x, mask=[1,0,0,0,0,0])
masked_array.mean()

2.5


3.0

In [77]:
x = np.arange(25, dtype = float).reshape(5,5)
x[x<5] = np.nan
x

array([[nan, nan, nan, nan, nan],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

In [78]:
np.where(np.isnan(x), ma.array(x, mask=np.isnan(x)).mean(axis=0), x)

array([[12.5, 13.5, 14.5, 15.5, 16.5],
       [ 5. ,  6. ,  7. ,  8. ,  9. ],
       [10. , 11. , 12. , 13. , 14. ],
       [15. , 16. , 17. , 18. , 19. ],
       [20. , 21. , 22. , 23. , 24. ]])

# Indexing, Slicing, Reshaping, Resizing, Broadcasting

In [79]:
x = ["USA","France", "Germany","England"]
x[2]

'Germany'

In [80]:
x = ('USA',3,"France",4)
x[2]

'France'

In [81]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
x[5]

5

In [83]:
x[-2]

8

In [84]:
x[2:8]

array([2, 3, 4, 5, 6, 7])

In [85]:
x[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
x[2:8:2]

array([2, 4, 6])

In [87]:
x = np.reshape(np.arange(16),(4,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [88]:
x[1:3]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [89]:
x[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [90]:
x[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [91]:
x = np.reshape(np.arange(16),(4,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [92]:
x[[0,1,2],[0,1,3]]

array([ 0,  5, 11])

In [93]:
x = np.arange(16).reshape(4,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [94]:
np.resize(x,(2,2))

array([[0, 1],
       [2, 3]])

In [95]:
np.resize(x,(6,6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15,  0,  1],
       [ 2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13],
       [14, 15,  0,  1,  2,  3]])

In [96]:
x = np.arange(16).reshape(4,4)
y = np.arange(6).reshape(2,3)
x+y

ValueError: operands could not be broadcast together with shapes (4,4) (2,3) 

In [97]:
x = np.ones(16).reshape(4,4)
y = np.arange(4)
x*y

array([[0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.]])

In [98]:
x = np.arange(4).reshape(2,2)
x

array([[0, 1],
       [2, 3]])

In [99]:
y = np.arange(2).reshape(1,2)
y

array([[0, 1]])

In [100]:
x*y

array([[0, 1],
       [0, 3]])